// a_samp
REGISTER_LONG_CONSTANT("CAMERA_MOVE", CAMERA_MOVE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CAMERA_CUT", CAMERA_CUT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("INVALID_PLAYER_ID", INVALID_PLAYER_ID, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_PLAYER_NAME", MAX_PLAYER_NAME, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_PLAYERS", MAX_PLAYERS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_VEHICLES", MAX_VEHICLES, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("INVALID_VEHICLE_ID", INVALID_VEHICLE_ID, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("NO_TEAM", NO_TEAM, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("INVALID_OBJECT_ID", INVALID_OBJECT_ID, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_OBJECTS", MAX_OBJECTS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_GANG_ZONES", MAX_GANG_ZONES, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_TEXT_DRAWS", MAX_TEXT_DRAWS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_PLAYER_TEXT_DRAWS", MAX_PLAYER_TEXT_DRAWS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_MENUS", MAX_MENUS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_3DTEXT_GLOBAL", MAX_3DTEXT_GLOBAL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_3DTEXT_PLAYER", MAX_3DTEXT_PLAYER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAX_PICKUPS", MAX_PICKUPS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("INVALID_MENU", INVALID_MENU, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("INVALID_TEXT_DRAW", INVALID_TEXT_DRAW, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("INVALID_GANG_ZONE", INVALID_GANG_ZONE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("INVALID_3DTEXT_ID", INVALID_3DTEXT_ID, CONST_CS | CONST_PERSISTENT);
// Text Draw
REGISTER_LONG_CONSTANT("TEXT_DRAW_FONT_SPRITE_DRAW", TEXT_DRAW_FONT_SPRITE_DRAW, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("TEXT_DRAW_FONT_MODEL_PREVIEW", TEXT_DRAW_FONT_MODEL_PREVIEW, CONST_CS | CONST_PERSISTENT);
// Player GUI Dialog
REGISTER_LONG_CONSTANT("DIALOG_STYLE_MSGBOX", DIALOG_STYLE_MSGBOX, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("DIALOG_STYLE_INPUT", DIALOG_STYLE_INPUT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("DIALOG_STYLE_LIST", DIALOG_STYLE_LIST, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("DIALOG_STYLE_PASSWORD", DIALOG_STYLE_PASSWORD, CONST_CS | CONST_PERSISTENT);

// States
REGISTER_LONG_CONSTANT("PLAYER_STATE_NONE", PLAYER_STATE_NONE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_STATE_ONFOOT", PLAYER_STATE_ONFOOT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_STATE_DRIVER", PLAYER_STATE_DRIVER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_STATE_PASSENGER", PLAYER_STATE_PASSENGER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_STATE_EXIT_VEHICLE", PLAYER_STATE_EXIT_VEHICLE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_STATE_ENTER_VEHICLE_DRIVER", PLAYER_STATE_ENTER_VEHICLE_DRIVER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_STATE_ENTER_VEHICLE_PASSENGER", PLAYER_STATE_ENTER_VEHICLE_PASSENGER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_STATE_WASTED", PLAYER_STATE_WASTED, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_STATE_SPAWNED", PLAYER_STATE_SPAWNED, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_STATE_SPECTATING", PLAYER_STATE_SPECTATING, CONST_CS | CONST_PERSISTENT);

// Marker modes used by ShowPlayerMarkers()
REGISTER_LONG_CONSTANT("PLAYER_MARKERS_MODE_OFF", PLAYER_MARKERS_MODE_OFF, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_MARKERS_MODE_GLOBAL", PLAYER_MARKERS_MODE_GLOBAL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_MARKERS_MODE_STREAMED", PLAYER_MARKERS_MODE_STREAMED, CONST_CS | CONST_PERSISTENT);

// Weapons
REGISTER_LONG_CONSTANT("WEAPON_BRASSKNUCKLE", WEAPON_BRASSKNUCKLE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_GOLFCLUB", WEAPON_GOLFCLUB, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_NITESTICK", WEAPON_NITESTICK, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_KNIFE", WEAPON_KNIFE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_BAT", WEAPON_BAT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_SHOVEL", WEAPON_SHOVEL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_POOLSTICK", WEAPON_POOLSTICK, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_KATANA", WEAPON_KATANA, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_CHAINSAW", WEAPON_CHAINSAW, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_DILDO", WEAPON_DILDO, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_DILDO2", WEAPON_DILDO2, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_VIBRATOR", WEAPON_VIBRATOR, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_VIBRATOR2", WEAPON_VIBRATOR2, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_FLOWER", WEAPON_FLOWER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_CANE", WEAPON_CANE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_GRENADE", WEAPON_GRENADE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_TEARGAS", WEAPON_TEARGAS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_MOLTOV", WEAPON_MOLTOV, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_COLT45", WEAPON_COLT45, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_SILENCED", WEAPON_SILENCED, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_DEAGLE", WEAPON_DEAGLE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_SHOTGUN", WEAPON_SHOTGUN, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_SAWEDOFF", WEAPON_SAWEDOFF, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_SHOTGSPA", WEAPON_SHOTGSPA, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_UZI", WEAPON_UZI, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_MP5", WEAPON_MP5, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_AK47", WEAPON_AK47, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_M4", WEAPON_M4, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_TEC9", WEAPON_TEC9, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_RIFLE", WEAPON_RIFLE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_SNIPER", WEAPON_SNIPER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_ROCKETLAUNCHER", WEAPON_ROCKETLAUNCHER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_HEATSEEKER", WEAPON_HEATSEEKER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_FLAMETHROWER", WEAPON_FLAMETHROWER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_MINIGUN", WEAPON_MINIGUN, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_SATCHEL", WEAPON_SATCHEL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_BOMB", WEAPON_BOMB, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_SPRAYCAN", WEAPON_SPRAYCAN, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_FIREEXTINGUISHER", WEAPON_FIREEXTINGUISHR, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_CAMERA", WEAPON_CAMERA, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_PARACHUTE", WEAPON_PARACHUTE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_VEHICLE", WEAPON_VEHICLE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_DROWN", WEAPON_DROWN, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPON_COLLISION", WEAPON_COLLISION, CONST_CS | CONST_PERSISTENT);

// Keys
REGISTER_LONG_CONSTANT("KEY_ACTION", KEY_ACTION, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_CROUCH", KEY_CROUCH, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_FIRE", KEY_FIRE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_SPRINT", KEY_SPRINT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_SECONDARY_ATTACK", KEY_SECONDARY_ATTACK, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_JUMP", KEY_JUMP, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_LOOK_RIGHT", KEY_LOOK_RIGHT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_HANDBRAKE", KEY_HANDBRAKE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_LOOK_LEFT", KEY_LOOK_LEFT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_SUBMISSION", KEY_SUBMISSION, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_LOOK_BEHIND", KEY_LOOK_BEHIND, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_WALK", KEY_WALK, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_ANALOG_UP", KEY_ANALOG_UP, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_ANALOG_DOWN", KEY_ANALOG_DOWN, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_ANALOG_LEFT", KEY_ANALOG_LEFT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_ANALOG_RIGHT", KEY_ANALOG_RIGHT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_YES", KEY_YES, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_NO", KEY_NO, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_CTRL_BACK", KEY_CTRL_BACK, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("KEY_UP", KEY_UP, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_DOWN", KEY_DOWN, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_LEFT", KEY_LEFT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("KEY_RIGHT", KEY_RIGHT, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("CLICK_SOURCE_SCOREBOARD", CLICK_SOURCE_SCOREBOARD, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("EDIT_RESPONSE_CANCEL", EDIT_RESPONSE_CANCEL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("EDIT_RESPONSE_FINAL", EDIT_RESPONSE_FINAL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("EDIT_RESPONSE_UPDATE", EDIT_RESPONSE_UPDATE, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("SELECT_OBJECT_GLOBAL_OBJECT", SELECT_OBJECT_GLOBAL_OBJECT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SELECT_OBJECT_PLAYER_OBJECT", SELECT_OBJECT_PLAYER_OBJECT, CONST_CS | CONST_PERSISTENT);

// a_vehicles
// Vehicles
REGISTER_LONG_CONSTANT("CARMODTYPE_SPOILER", CARMODTYPE_SPOILER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_HOOD", CARMODTYPE_HOOD, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_ROOF", CARMODTYPE_ROOF, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_SIDESKIRT", CARMODTYPE_SIDESKIRT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_LAMPS", CARMODTYPE_LAMPS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_NITRO", CARMODTYPE_NITRO, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_EXHAUST", CARMODTYPE_EXHAUST, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_WHEELS", CARMODTYPE_WHEELS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_STEREO", CARMODTYPE_STEREO, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_HYDRAULICS", CARMODTYPE_HYDRAULICS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_FRONT_BUMPER", CARMODTYPE_FRONT_BUMPER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_REAR_BUMPER", CARMODTYPE_REAR_BUMPER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_VENT_RIGHT", CARMODTYPE_VENT_RIGHT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("CARMODTYPE_VENT_LEFT", CARMODTYPE_VENT_LEFT, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("VEHICLE_PARAMS_UNSET", VEHICLE_PARAMS_UNSET, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("VEHICLE_PARAMS_OFF", VEHICLE_PARAMS_OFF, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("VEHICLE_PARAMS_ON", VEHICLE_PARAMS_ON, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("VEHICLE_MODEL_INFO_SIZE", VEHICLE_MODEL_INFO_SIZE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("VEHICLE_MODEL_INFO_FRONTSEAT", VEHICLE_MODEL_INFO_FRONTSEAT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("VEHICLE_MODEL_INFO_REARSEAT", VEHICLE_MODEL_INFO_REARSEAT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("VEHICLE_MODEL_INFO_PETROLCAP", VEHICLE_MODEL_INFO_PETROLCAP, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("VEHICLE_MODEL_INFO_WHEELSFRONT", VEHICLE_MODEL_INFO_WHEELSFRONT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("VEHICLE_MODEL_INFO_WHEELSREAR", VEHICLE_MODEL_INFO_WHEELSREAR, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("VEHICLE_MODEL_INFO_WHEELSMID", VEHICLE_MODEL_INFO_WHEELSMID, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("VEHICLE_MODEL_INFO_FRONT_BUMPER_Z", VEHICLE_MODEL_INFO_FRONT_BUMPER_Z, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("VEHICLE_MODEL_INFO_REAR_BUMPER_Z", VEHICLE_MODEL_INFO_REAR_BUMPER_Z, CONST_CS | CONST_PERSISTENT);


// a_player
// Player
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_NONE", SPECIAL_ACTION_NONE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_DUCK", SPECIAL_ACTION_DUCK, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_USEJETPACK", SPECIAL_ACTION_USEJETPACK, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_ENTER_VEHICLE", SPECIAL_ACTION_ENTER_VEHICLE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_EXIT_VEHICLE", SPECIAL_ACTION_EXIT_VEHICLE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_DANCE1", SPECIAL_ACTION_DANCE1, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_DANCE2", SPECIAL_ACTION_DANCE2, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_DANCE3", SPECIAL_ACTION_DANCE3, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_DANCE4", SPECIAL_ACTION_DANCE4, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_HANDSUP", SPECIAL_ACTION_HANDSUP, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_USECELLPHONE", SPECIAL_ACTION_USECELLPHONE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_SITTING", SPECIAL_ACTION_SITTING, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_STOPUSECELLPHONE", SPECIAL_ACTION_STOPUSECELLPHONE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_DRINK_BEER", SPECIAL_ACTION_DRINK_BEER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_SMOKE_CIGGY", SPECIAL_ACTION_SMOKE_CIGGY, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_DRINK_WINE", SPECIAL_ACTION_DRINK_WINE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_DRINK_SPRUNK", SPECIAL_ACTION_DRINK_SPRUNK, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_CUFFED", SPECIAL_ACTION_CUFFED, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECIAL_ACTION_CARRY", SPECIAL_ACTION_CARRY, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("FIGHT_STYLE_NORMAL", FIGHT_STYLE_NORMAL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("FIGHT_STYLE_BOXING", FIGHT_STYLE_BOXING, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("FIGHT_STYLE_KUNGFU", FIGHT_STYLE_KUNGFU, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("FIGHT_STYLE_KNEEHEAD", FIGHT_STYLE_KNEEHEAD, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("FIGHT_STYLE_GRABKICK", FIGHT_STYLE_GRABKICK, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("FIGHT_STYLE_ELBOW", FIGHT_STYLE_ELBOW, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("WEAPONSKILL_PISTOL", WEAPONSKILL_PISTOL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSKILL_PISTOL_SILENCED", WEAPONSKILL_PISTOL_SILENCED, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSKILL_DESERT_EAGLE", WEAPONSKILL_DESERT_EAGLE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSKILL_SHOTGUN", WEAPONSKILL_SHOTGUN, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSKILL_SAWNOFF_SHOTGUN", WEAPONSKILL_SAWNOFF_SHOTGUN, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSKILL_SPAS12_SHOTGUN", WEAPONSKILL_SPAS12_SHOTGUN, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSKILL_MICRO_UZI", WEAPONSKILL_MICRO_UZI, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSKILL_MP5", WEAPONSKILL_MP5, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSKILL_AK47", WEAPONSKILL_AK47, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSKILL_M4", WEAPONSKILL_M4, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSKILL_SNIPERRIFLE", WEAPONSKILL_SNIPERRIFLE, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("WEAPONSTATE_UNKNOWN", WEAPONSTATE_UNKNOWN, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSTATE_NO_BULLETS", WEAPONSTATE_NO_BULLETS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSTATE_LAST_BULLET", WEAPONSTATE_LAST_BULLET, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSTATE_MORE_BULLETS", WEAPONSTATE_MORE_BULLETS, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("WEAPONSTATE_RELOADING", WEAPONSTATE_RELOADING, CONST_CS | CONST_PERSISTENT);

// Attached to bone objects
REGISTER_LONG_CONSTANT("MAX_PLAYER_ATTACHED_OBJECTS", MAX_PLAYER_ATTACHED_OBJECTS, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("MAX_CHATBUBBLE_LENGTH", MAX_CHATBUBBLE_LENGTH, CONST_CS | CONST_PERSISTENT);

// Player world/map related
REGISTER_LONG_CONSTANT("MAPICON_LOCAL", MAPICON_LOCAL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAPICON_GLOBAL", MAPICON_GLOBAL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAPICON_LOCAL_CHECKPOINT", MAPICON_LOCAL_CHECKPOINT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("MAPICON_GLOBAL_CHECKPOINT", MAPICON_GLOBAL_CHECKPOINT, CONST_CS | CONST_PERSISTENT);

// Spectating
REGISTER_LONG_CONSTANT("SPECTATE_MODE_NORMAL", SPECTATE_MODE_NORMAL, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECTATE_MODE_FIXED", SPECTATE_MODE_FIXED, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SPECTATE_MODE_SIDE", SPECTATE_MODE_SIDE, CONST_CS | CONST_PERSISTENT);

// Recording for NPC playback
REGISTER_LONG_CONSTANT("PLAYER_RECORDING_TYPE_NONE", PLAYER_RECORDING_TYPE_NONE, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_RECORDING_TYPE_DRIVER", PLAYER_RECORDING_TYPE_DRIVER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("PLAYER_RECORDING_TYPE_ONFOOT", PLAYER_RECORDING_TYPE_ONFOOT, CONST_CS | CONST_PERSISTENT);

// a_object
// Objects
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_32x32", OBJECT_MATERIAL_SIZE_32x32, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_64x32", OBJECT_MATERIAL_SIZE_64x32, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_64x64", OBJECT_MATERIAL_SIZE_64x64, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_128x32", OBJECT_MATERIAL_SIZE_128x32, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_128x64", OBJECT_MATERIAL_SIZE_128x64, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_128x128", OBJECT_MATERIAL_SIZE_128x128, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_256x32", OBJECT_MATERIAL_SIZE_256x32, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_256x64", OBJECT_MATERIAL_SIZE_256x64, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_256x128", OBJECT_MATERIAL_SIZE_256x128, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_256x256", OBJECT_MATERIAL_SIZE_256x256, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_512x64", OBJECT_MATERIAL_SIZE_512x64, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_512x128", OBJECT_MATERIAL_SIZE_512x128, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_512x256", OBJECT_MATERIAL_SIZE_512x256, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_SIZE_512x512", OBJECT_MATERIAL_SIZE_512x512, CONST_CS | CONST_PERSISTENT);

REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_TEXT_ALIGN_LEFT", OBJECT_MATERIAL_TEXT_ALIGN_LEFT, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_TEXT_ALIGN_CENTER", OBJECT_MATERIAL_TEXT_ALIGN_CENTER, CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("OBJECT_MATERIAL_TEXT_ALIGN_RIGHT", OBJECT_MATERIAL_TEXT_ALIGN_RIGHT, CONST_CS | CONST_PERSISTENT);


